//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_Entity_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories2
    {
        public string CategoryName { get; set; }
    }
}
